export const medicamentosQuery = (ingreso: number) => {
  return ` 
SELECT 
N0.OID AS ID, 
N2.ADNINGRESO AS INGRESO, 
N2.HCNUMFOL  AS FOLIO, 
N1.IPRCODIGO AS CODIGO, 
N1.IPRDESCOR AS DESCRIPCION, 
N0.HCSCANTI AS CANTIDAD, 
N0."HCNESTFORM" AS CODIGO_ESTADO,
CASE N0."HCNESTFORM" 
WHEN 0 THEN 'ACTIVA' 
WHEN 1 THEN 'FINALIZADA' 
WHEN 2 THEN 'SUSPENDIDA' 
WHEN 3 THEN 'VENCIDA' 
END AS ESTADO
FROM ((("DBO"."HCNMEDPAC" N0 WITH (NOLOCK)
 LEFT JOIN "DBO"."INNPRODUC" N1 WITH (NOLOCK) ON (N0."INNPRODUC" = N1."OID"))
 LEFT JOIN "DBO"."INNUNIDAD" N8 WITH (NOLOCK) ON (N1."INNUNIDADD" = N8."OID"))
 LEFT JOIN "DBO"."HCNFOLIO" N2 WITH (NOLOCK) ON (N0."HCNFOLIO" = N2."OID"))
 WHERE  ((N2."HCFOLABR" = 0) AND (N2."ADNINGRESO" = ${ingreso}) AND (N0."HCSINTRAH" = 1) AND ((N0."HCPTIPORD" = 0) OR (N0."HCPTIPORD" = 4)))
  `;
};
