import { GEN_MODULES } from './_common';

export const SEC_AUTHORITIES = {
  CODE: GEN_MODULES.CODE,
  ADMIN: `${GEN_MODULES.CODE}001`,
  SECURITY: {
    ADMIN: `${GEN_MODULES.SUBS.SECURITY}001`,
  },
  AUTHORITIES: {
    CODE: GEN_MODULES.SUBS.AUTHORITIES,
    MANAGE_ALL_AUTHORITIES: `${GEN_MODULES.SUBS.AUTHORITIES}001`,
    CREATE_AUTHORITIES: `${GEN_MODULES.SUBS.AUTHORITIES}002`,
  },
};
