import { HPN_MODULES } from './_common';

export const HPN_AUTHORITIES = {
  CODE: HPN_MODULES.CODE,
  DIETAS: {
    CODE: `${HPN_MODULES.SUBS.DIETAS}`,
    REGISTRAR: `${HPN_MODULES.SUBS.DIETAS}001`,
    VER_JORNADA: `${HPN_MODULES.SUBS.DIETAS}002`,
    FUNCIONES_PROVEEDOR: `${HPN_MODULES.SUBS.DIETAS}003`,
    ASIGNAR_EXTRAORDINARIAS: `${HPN_MODULES.SUBS.DIETAS}004`,
    RECIBIR_EN_DESTINO: `${HPN_MODULES.SUBS.DIETAS}005`,
    REPORTAR_FALTANTES: `${HPN_MODULES.SUBS.DIETAS}006`,
    VER_FACTURACION: `${HPN_MODULES.SUBS.DIETAS}007`,
    REGISTRAR_IGNORA_JORNADA: `${HPN_MODULES.SUBS.DIETAS}008`,
  },
  GESTION_CLINICA: {
    CODE: `${HPN_MODULES.SUBS.GESTION_CLINICA}`,
    GESTIONAR_AREAS: `${HPN_MODULES.SUBS.GESTION_CLINICA}001`,
    ADMINISTRAR_GESTIONES: `${HPN_MODULES.SUBS.GESTION_CLINICA}002`,
    GESTIONAR_PACIENTES: `${HPN_MODULES.SUBS.GESTION_CLINICA}003`,
    TIEMPOS_EGRESOS: `${HPN_MODULES.SUBS.GESTION_CLINICA}004`,
    REPORTE_VALORES_CRITICOS: `${HPN_MODULES.SUBS.GESTION_CLINICA}005`,
    VER_TODOS_REPO_VAL_CRI: `${HPN_MODULES.SUBS.GESTION_CLINICA}006`,
    AUDITAR_REPORTE_VALORES_CRITICOS: `${HPN_MODULES.SUBS.GESTION_CLINICA}007`,
    GESTIONAR_TRANSLADO_ASIGNADOS: `${HPN_MODULES.SUBS.GESTION_CLINICA}008`,
    REGI_ASIGNAR_MOVIL: `${HPN_MODULES.SUBS.GESTION_CLINICA}009`,
    ENTREGA_TURNO: `${HPN_MODULES.SUBS.GESTION_CLINICA}010`,
    GESTION_TURNO: `${HPN_MODULES.SUBS.GESTION_CLINICA}011`,
  },
  CAMAS: {
    RESERVA: `${HPN_MODULES.SUBS.CAMAS}001`,
    VER_CAMAS: `${HPN_MODULES.SUBS.CAMAS}002`,
  },
  CENSOS: {
    CODE: `${HPN_MODULES.SUBS.CENSOS}`,
    PACIENTES: `${HPN_MODULES.SUBS.CENSOS}001`,
    CAMAS: `${HPN_MODULES.SUBS.CENSOS}002`,
  },
  TRIAGE: {
    CODE: `${HPN_MODULES.SUBS.TRIAGE}`,
    TABLERO: `${HPN_MODULES.SUBS.TRIAGE}001`,
  },
  APIS: {
    CODE: `${HPN_MODULES.SUBS.APIS}`,
    RECORDATORIO_CITAS: `${HPN_MODULES.SUBS.APIS}001`,
  },
  AUDITORIA: {
    CODE: `${HPN_MODULES.SUBS.AUDITORIA}`,
    GESTIONAR: `${HPN_MODULES.SUBS.AUDITORIA}001`,
  },
  PACIENTES: {
    CODE: `${HPN_MODULES.SUBS.PACIENTES}`,
    ENCUESTA_PACIENTE_TRAZADOR: `${HPN_MODULES.SUBS.PACIENTES}001`,
  },
};
